Readme polishing
spring-cloud-stream-app-starters/log pull request #1
Opened 2017-08-15 19:08 UTC by sobychacko

Related to spring-cloud-stream-app-starters/app-starters-release#99

2017-08-15 20:35 UTC, artembilan requested changes

2017-08-15 20:35 UTC, artembilan commented on spring-cloud-starter-stream-sink-log/README.adoc
> +A `String` representation of the logging message.
I think that's not true.
Any object with any content-type can be used for the logging.
Just see all those `Log`  methods!
```
    /**
     * Logs a message with debug log level.
     *
     * @param message log this message
     */
    void debug(Object message);
```

2017-08-22 07:59 UTC, ericbottard commented on spring-cloud-starter-stream-sink-log/README.adoc
> +You can find the corresponding binder based projects here. You can then cd into one one of the folders and build it:
This sentence needs to be moved out of the code block

2017-08-23 00:25 UTC, sobychacko commented
merged.

2017-08-23 00:25 UTC, closed without merging